### ISSUE TITLE
Code repo and how to easily make sure bugs/fr become tasks

### ISSUE THREAD

**Issue by zaibon** [Incubaid/dev_process#27]
In the description of the code repo it says:

> DO NOT
> use stories or tasks or tests at this level !!!

Then 

> how to easily make sure bugs/fr become tasks
> put unique story card name at beginning of title e.g. story1:...
> the incubaid development process tools will find the story and if found create a task for it and put this bug/fr in as task (in the task there will be link to this bug/fr)

I think this is wrong. There is not stories defined in a code repo, so you can't just prepend
preprend the issue with a story name. The dev process tools doesn't work over multiple repos for linking stories and tasks. 

I think the correct flow is, ones a bug is accepted, someone need to create a task or story about it in the org_dev repo and link the bug to it. Then from there the dev process tools can start working.

**Comment by wimpers** [comment]
@zaibon, I would assume that if you add 'storycardname:' in front of the bug/FR that it automatically creates a task in the org_development repo. I don't thinkt it needs to create the task inside the same code repo. It is the org_development repo that hold the storycards.

**Comment by FastGeert** [comment]
@wimpers It is the task of the BAM meeting to decide wether and when a certain bug / fr will be picked up. Also in the case of bugs, groups of related bugs should be grouped into a logical task to be solved instead of just being copied as single tasks. 
@despiegk please correct me if I'm wrong about this.

**Comment by wimpers** [comment]
@FastGeert I tend to disagree. The BAM decides the release milestone. It should not be up to the BAM to decide the storycard. That is the task of the storycard/product owner to group bugs and FR according to the time available. 

For example let's pick the Fargo release. As a Product Manager I want something to be fixed in Fargo but I don't want to micromanage in which week/month (or however you plan a storycard) they fix it. I don't want to tell f.e. the teamlead of the Framework when he needs to schedule a bug as he is ultimately responsible for delivering all content for a release for his part of the product.

See https://gig.gitbooks.io/agile/content/meetings.html

> go over all the open issues, set priorities and attach issues to a certain **milestone**

**Comment by FastGeert** [comment]
@wimpers As a product owner I would not like that people are able to just force their FR into the developers planning without me knowing about it.

**Comment by wimpers** [comment]
After short-cut discussion with @FastGeert and to clarify the above points:
- The creator of the FR/bug should **NOT** add the 'storycardname:'.
- Only storycard owner (in most cases the product owner of that product) should set the the 'storycardname:' to the title of the bug/FR.
